version: "3.9"
services:
  web:
    build: .
    env_file:
      - ./config/.env
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db
    networks:
      - go-network

  db:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    env_file:
      - ./config/.env
    expose:
      - 5432
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    networks:
      - go-network

networks:
  go-network:
    driver: bridge